import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppProvider from "@/providers/app-provider";

import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import JotaiProvider from "@/providers/jotai-provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "HireReady-Ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${inter.variable} ${inter.className}`}>
        <body>
          
          <AppProvider>
            <JotaiProvider>
            {children}
            </JotaiProvider>
            </AppProvider>
          <Toaster position="bottom-right" />
        </body>
      </html>
    </ClerkProvider>
  );
}
